version: '3'
services:
  tg_proxy:
    image: nineseconds/mtg:2
    container_name: tg_proxy
    restart: unless-stopped
    ports:
      - "8443:3128"
    environment:
      - MTG_SECRET=${TG_SECRET}
      - MTG_BIND_ADR=0.0.0.0:3128
    command: run

