services:
  mtproto-proxy:
    image: telegrammessenger/proxy
    container_name: mtproto-proxy
    restart: always
    ports:
      - "8443:443"
    environment:
      - SECRET=
      - IP=109.195.103.194
      - AES_ONLY=1
    volumes:
      - proxy-config:/data
